childBlocks: null
conditions: null
description: ''
enabled: true
field: 71f89410-1606-4a6b-9bda-9800190d50e7 # Page Content
fieldLayouts:
  24523c7a-e051-4251-a546-8b1521e31692:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 2034444b-6198-419d-b095-47b61f9bd6f4 # Headline Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 036435ea-2586-4120-af4c-8a3c6f76e62c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ea70283d-a91d-4691-8ea9-e5bfaaf710e4 # Link Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc94df96-ddd6-4575-87b7-9635ad9b188e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: d7d708bb-8ba2-495d-b8f6-8058568f4b6d # Link URL
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9dfdb032-5afb-47ee-928a-0692b5c97de2
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 4a6a5fcc-737e-41f7-aad3-edda9c3c2415
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8d7ed899-0b48-4c06-bcdd-e008669ba816 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 609f0b20-dd1f-45f9-85aa-7d72bc73b546
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f4e4146-2f51-44be-8552-754fd70284de # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65fae12f-f8c8-4c9c-aee7-0199458f372f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 919100a9-720f-4942-bce5-a77a42069891 # Background Noise
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c62db9cc-d9f3-499e-862f-fdff6c693650
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ea0dce0-c302-4f93-871c-133aa14cf60e # Text Color Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6471cee6-9198-4095-8d68-708ce54e3033
            userCondition: null
            warning: null
            width: 100
        name: Design
        uid: d02f66ef-2d3b-43b9-b3ca-974db09ce96c
        userCondition: null
group: null
groupChildBlockTypes: true
handle: imageCTA
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Image CTA'
sortOrder: 4
topLevel: true
