childBlocks: null
conditions: null
description: ''
enabled: true
field: 71f89410-1606-4a6b-9bda-9800190d50e7 # Page Content
fieldLayouts:
  ec5c3b5a-0536-4099-96c1-895ea212d99d:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3fde6c7e-8cd8-4fc2-9adb-9d5c6d555cb4 # Section Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c5a0257f-1c66-4870-86d5-7734a341fc14
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2034444b-6198-419d-b095-47b61f9bd6f4 # Headline Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a670e87a-99cd-4bcc-b15f-bdf753e14690
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: e21d2283-562d-4246-9ec9-4d6003ef1bcd # Intro Text
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5c56c3da-e29f-4d40-9bd6-4f7f63b301fe
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5bf6bb5d-97f3-4ab5-94cc-c77be198053f # Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 248977dc-2104-4af9-bcc9-d420e032d2b7
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 09bfa9cf-be4a-41e3-95dc-f91bd80e861a # Intro Text Columns
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c7c39b80-1227-4e1a-9ded-b58519bb3673
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a65fa8d-8f11-4f88-abb1-743c7ee35f8f # Section Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 71d9951b-02f7-4b2d-b613-8183bbd18000
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 637db1c7-ceac-488b-a574-8d673e7d962a
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 5f4e4146-2f51-44be-8552-754fd70284de # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4b40c925-310d-4bc9-9117-a457501aa32a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 919100a9-720f-4942-bce5-a77a42069891 # Background Noise
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e16f73e7-5ca6-41b9-a9d2-2cf9f95e1494
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ea0dce0-c302-4f93-871c-133aa14cf60e # Text Color Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c8f4a1cd-e4d9-4478-a752-1d5f6e45e1b6
            userCondition: null
            warning: null
            width: 100
        name: Design
        uid: a7c9952b-718f-46fa-8066-6aa24130e9fa
        userCondition: null
group: null
groupChildBlockTypes: true
handle: introText
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Intro Text'
sortOrder: 1
topLevel: true
