childBlocks: null
conditions: null
description: ''
enabled: true
field: 71f89410-1606-4a6b-9bda-9800190d50e7 # Page Content
fieldLayouts:
  a1a9e0e9-afee-4584-9e60-111732966031:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3fde6c7e-8cd8-4fc2-9adb-9d5c6d555cb4 # Section Content
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4f179424-b158-406e-bb57-495d74765c95
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2c76eea1-b58d-48b7-8ea3-fe8769399236 # Left Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fc3a9b51-7083-4912-97f6-09eeeb752712
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 05a36ec6-adbf-482e-b3d8-d231e6369240 # Right Headline
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4e7f3af-7886-4062-a7e7-c43fcfa55ce4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 0edebd3c-4b85-4fe6-9279-c80f05253dae # Bullet Text List
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 24ffda82-a3b9-4eb7-84fd-f56a6dc95717
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9a65fa8d-8f11-4f88-abb1-743c7ee35f8f # Section Link
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b1bd3457-3f69-4090-9005-f80f22b36f36
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 360b6fa9-d35e-43e5-9902-217aa32b485d
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 8d7ed899-0b48-4c06-bcdd-e008669ba816 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 609f0b20-dd1f-45f9-85aa-7d72bc73b546
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5f4e4146-2f51-44be-8552-754fd70284de # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65fae12f-f8c8-4c9c-aee7-0199458f372f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 919100a9-720f-4942-bce5-a77a42069891 # Background Noise
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c62db9cc-d9f3-499e-862f-fdff6c693650
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 8ea0dce0-c302-4f93-871c-133aa14cf60e # Text Color Theme
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6471cee6-9198-4095-8d68-708ce54e3033
            userCondition: null
            warning: null
            width: 100
        name: Design
        uid: ed6dbbfb-c16e-4680-b81a-ec3543528ec7
        userCondition: null
group: null
groupChildBlockTypes: true
handle: sideBySideList
icon: null
ignorePermissions: true
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
minBlocks: 0
minChildBlocks: 0
minSiblingBlocks: 0
name: 'Side By Side List'
sortOrder: 3
topLevel: true
