columnSuffix: null
contentColumnType: string
fieldGroup: 71f23d0c-7806-490f-a3f3-7cde516ac254 # Page Builder
handle: hero
instructions: null
name: Hero
searchable: false
settings:
  maxBlocks: 1
  maxLevels: null
  maxTopBlocks: null
  minBlocks: 1
  minLevels: null
  minTopBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
