columnSuffix: cpwifsrv
contentColumnType: string(255)
fieldGroup: 234b64bf-47dc-4ece-80f7-c0d6805ac11e # Content Entry Fields
handle: linkURL
instructions: null
name: 'Link URL'
searchable: false
settings:
  maxLength: 255
  types:
    - url
    - tel
    - email
translationKeyFormat: null
translationMethod: none
type: craft\fields\Url
