columnSuffix: null
contentColumnType: string
fieldGroup: 234b64bf-47dc-4ece-80f7-c0d6805ac11e # Content Entry Fields
handle: sectionContent
instructions: null
name: 'Section Content'
searchable: false
settings:
  contentTable: '{{%matrixcontent_sectioncontent}}'
  maxBlocks: 1
  minBlocks: null
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
