columnSuffix: ywinicgv
contentColumnType: string(5)
fieldGroup: 234b64bf-47dc-4ece-80f7-c0d6805ac11e # Content Entry Fields
handle: textColorTheme
instructions: null
name: 'Text Color Theme'
searchable: false
settings:
  columnType: null
  options:
    -
      __assoc__:
        -
          - label
          - Light
        -
          - value
          - light
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Dark
        -
          - value
          - dark
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
