defaultPlacement: end
enableVersioning: true
handle: transactions
name: Transactions
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  999bbe58-90cd-478b-9db9-f355c5563ad4: # Encore AMC
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: 'transactions/{slug}'
type: channel
